kind: pipeline
name: default

clone:
  skip_verify: true

limit:
  concurrency: 1

steps:
- name: mirror
  image: alpine/git
  commands:
  - git push --mirror https://$$LOGIN@github.com/dragonfruitnetwork/onionfruit.git
  environment:
    LOGIN:
      from_secret: GIT
- name: deploy
  image: node
  environment:
    FIREBASE_TOKEN:
      from_secret: FIREBASE_TOKEN
  commands:
  - npm install -g firebase-tools
  - firebase deploy --token "$${FIREBASE_TOKEN}" --project "onionfruit-connect"