kind: pipeline
name: default

steps:
- name: deploy
  image: google/drone-firebase
  environment:
    FIREBASE_TOKEN:
      from_secret: token
  commands:
  - firebase deploy --token "$FIREBASE_TOKEN"