kind: pipeline
name: default

clone:
  skip_verify: true

steps:
- name: deploy
  image: google/drone-firebase
  environment:
    FIREBASE_TOKEN:
      from_secret: FIREBASE_TOKEN
  commands:
  - echo "$${FIREBASE_TOKEN}"
  - firebase deploy --token "$${FIREBASE_TOKEN}" --project "onionfruit-connect"