kind: pipeline
name: default

clone:
  skip_verify: true

steps:
- name: deploy
  image: node
  environment:
    FIREBASE_TOKEN:
      from_secret: FIREBASE_TOKEN
  commands:
  - npm install -g firebase-tools
  - firebase deploy --token "$${FIREBASE_TOKEN}" --project "onionfruit-connect"